### PR TITLE
Add stub config for local nginx sites

### PR DESCRIPTION
**Pull request by lo5an**
* Sketches out basic support for local (unproxied) nginx sites and services, defined with the `nginx_local_sites` dictionary. 
* new config is basically literal site config with `s/literal/local/`

Motivation and Context
----------------------
Projects like the OneSearch search api gateway need to configure nginx. One straightforward way to do that is to have the nginx role configure a stub that will then be fully configured by the application role. 

This would let us separate out and standardize things like ssl configuration, while leaving  application specific config in the role for that application. 

How Has This Been Tested?
-------------------------
WORK IN PROGRESS, PR created for discussion of feature.

### CODE REVIEW

**Comment by jsnshrmn** [comment]
Having configuration stubs ain't a bad idea. I see no reason that their usefulness would be limited to localdomain sites.  Howabout
```
s/local/stub/g
s/\.conf/.conf.stub/g
```
files in conf.d that ends in in anything other than .conf will be ignored, so let's end stub config files in .stub.

**Comment by lo5an** [comment]
I'm definitely on board with the switch from `local` to `stub`. That's definitely more descriptive of what's happening. 

I'm not totally sure about switching from `.conf` to `.conf.stub`. I had pictured creating a minimum viable site config that would both serve as an example and provide a file to edit or replace. That said, the file that I'm currently delivering doesn't define any locations, so it's only 'viable' in that it properly 404s for all requests. That lets you test the name and SSL stuff, but doesn't get you much more than that. 

With the `.conf.stub` route, are you're thinking that we'd dump a file that we would include as a preamble to a an application role defined site config? I can see where that might be nice for decoupling the application roles from the nginx role, but it might be more natural to go the other way around. 

We could have the nginx role deliver a conf file something like:

```
server {
  listen              443;
  server_name         search;

  ssl                 on;
  ssl_certificate     /etc/pki/tls/certs/search/cert.pem;
  ssl_certificate_key /etc/pki/tls/private/search/privkey.pem;

  access_log          /var/log/nginx/search.access.log;

  # Application specific config for search
  include    /etc/nginx/search.conf.inc;

  # robots.txt overlay
  location =/robots.txt {
    alias             /srv/robots/robots.disallow.txt;
  }
```

That would leave log files, SSL, and the overall structure of things in a file controlled by the nginx role.

**Comment by jsnshrmn** [comment]
Okay, this include setup makes a lot of sense. Let's put the included file in /srv/app/etc and do an optional/conditional include of that configuration. That let's me off the hook for some undone/unconsidered tasks in the nginx role. Thanks for volunteering!

**Comment by lo5an** [comment]
I'm not finding a good way to do a conditional include of an nginx config file based on the existence of the file. It looks like the best bet will be something like 

```
  # Application provided config for search
  include /srv/searchgateway/etc/*.nginx.conf;
```

which is similar to where we're at with the Apache d7 stuff. It looks like it might be la little ess brittle in this context, though. Nginx seems better about handling paths and wildcards.  

It feels like this increases the coupling between the nginx role and dependent applications roles a little bit, but I'm not sure that's a big deal since the apps already depend on nginx.

**Comment by lo5an** [comment]
Just pushed commits to go along with my last comment.

**Review by jsnshrmn — APPROVED** [review]
This is exactly what we discussed, looks great.

**Pull request merged**
